version: '2'

services:
  db:
    image: mariadb:latest
    volumes:
      - "./db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: softbinator
      MYSQL_DATABASE: symfony2
      MYSQL_USER: symfony2
      MYSQL_PASSWORD: softbinator

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./symfony2:/symfony2
      - ./helpers:/helpers
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build:
      context: ./conf
      dockerfile: php.Dockerfile
    volumes:
      - ./symfony2:/symfony2
      - ./helpers:/helpers
    links:
      - db
